### ISSUE TITLE
Thanks for this but I am done with Lenovo

### ISSUE THREAD

**Issue by zouhair** [lenovo-inc/superfishremoval#2]
Never ever will you get my business.

**Comment by message** [comment]
That reminds me "I quit Facebook" rant :v:

**Comment by zouhair** [comment]
I don't use facebook either

**Comment by war59312** [comment]
+1 And same with FaceBook!

Both can go to hell!

**Comment by rubdos** [comment]
My two cents: buy Lenovo, send them spam about them preinstalling Windows, install Linux. It's my approach to it.

**Comment by cryptix** [comment]
also totally done. seconed hand is the only thing i would consider.

**Comment by IsaacWoods** [comment]
Nicely done @rubdos! Can't stand Windows - and this is just another reason why I will not use it. Lenovo have cost themselves dearly with this one.

**Comment by dwbfox** [comment]
@zouhair I know I'm going to get a lot of flack for this, but what Lenovo had done bundling Superfish is not unlike what other manufactures practice when selling low to mid range laptops and computers. They're a business and putting bloatware/adware in their machines is another revenue source for them. Boycotting one laptop manufacturer won't save you from bloatware from their competitors. Simply do what I do: obtain an OEM version of Windows and make a truly clean install. If you're that insistent on getting a "clean" OS experience, go for the higher-end ultra books.

**Comment by zouhair** [comment]
@dwbfox Maybe so, but this one is way more than just simple bloatware.

**Comment by IsaacWoods** [comment]
@dwbfox Or do it the proper way and just install Linux ;)

**Comment by xanather** [comment]
"Just install Linux" doesn't make sense for people who rely on programs that only work on Windows.

**Comment by patricebeutler** [comment]
Do you think my mom knows how to use this ;)?

**Comment by IsaacWoods** [comment]
@xanather That, I believe, is a very out-dated opinion. Sure, there are programs that don't work on Linux, but games apart, there are very few that don't have good replacements (usually without the price tag) or that can be run by using Wine, PlayOnLinux etc.

This is the price you put on having your nice bubble of propriety software - unless you want to pay an extra £50 you get bogged down by adware that the PC manufactures put on your system, and then you still need anti-virus software because the idiots at Microsoft haven't quite figured out how to not let random bits of unidentified software modify essential parts of your system.

And ease of use is not a problem any more - give anyone a version of Elementary OS or Ubuntu and they'll use it just fine. I honestly find Windows 8 more confusing.

**Comment by xanather** [comment]
@IsaacWoods 
"give anyone a version of Elementary OS or Ubuntu and they'll use it just fine" No they won't. The general PC userbase wants something that just works, they don't want to fiddle around with Wine only for the chance that it will work correctly and performant, and its the core reason why Linux popularity is still below 5% of the PC marketshare.

I do agree however, that that Windows as a OS is very vulnerable compared to Linux. I think this is mostly due to legacy program support and design decisions made early on (over 15 years ago).

I would love Linux to become the mainstream OS, believe me, it could improve the whole computing industry. However many just stick with windows since its still the path of least resistance. Hardware designers usually write drivers for windows first before looking at anything else, same with developers and software.

**Comment by IsaacWoods** [comment]
@xanather I agree. But they can't use that as an excuse, instead of reskinning a failure of a kernel used in Windows 95, Windows 10 should've been a complete rewrite - new kernel, new executable format (causing a lot of disturbance, sure, but cutting out the problem of legacy programs causing massive problems) and to design the userspace environment with proper permissions given to programs - basically cutting out the large majority of viruses and trogans). It's slowly getting worse and worse, and until that happens, it will never realistically get better.

And the Wine point was taking it to an extreme. What programs do you use on a daily basis that you think couldn't be replaced by an equivalent Linux program or online application?

And the point is - we have a catch 22 situation - we don't have a massive userbase, and therefore progress developing Linux-supporting applications is low. If more people used Linux, more applications would get developed for it and the ease-of-use would generally go up, which would get more people to use it.

**Comment by xanather** [comment]
@IsaacWoods Linux is just bad for the desktop. For servers it shines because of its simplicity, barebones kernel and not requiring a license for its use, you can customize a server to do exactly what it needs to do without anything else at all running on the system. Desktops PC's however are more general purpose and will usually always be doing multiple different functions at once, and in reality it is something that windows does well enough in its current state. I wish more would use Linux but it's hard to say if it will ever gain above 10% marketshare since its in the vicious adoption cycle you described and has been for quite some time.

**Comment by lenovo-inc** [comment]
Duplicate of #11
